#!/bin/bash

# Run lint before commit
npm run lint

# Run format before commit
npm run lint-fix

# generate uml diagram before commit
npm run uml

# Run tests before commit
npm run test

# Run build before commit
npm run build

# Package the library before commit
npm pack